server:
  port: 9110
spring:
  profiles:
    active: dev   #spring.profiles.active jar启动配置里更改环境
  application:
    name: comment-service
  mail:
    host: smtpdm.aliyun.com
    username: comment@shanbing.top
    password: ENC(YKLU2RsxlxqK562aiA8OTpqI89jw6Hra)
    default-encoding: utf-8
    # 阿里云服务25端口禁用，采用ssl加465端口
    properties:
      mail:
        smtp:
          auth: true
          timeout: 25000
          ssl.enable: true
          socketFactory.class: javax.net.ssl.SSLSocketFactory
          starttls.enable: true
          socketFactory.port: 465　
          port: 465





#mybatis相关配置
mybatis:
  mapperLocations: classpath:mapper/**/*.xml
  typeAliasesPackage: top.shanbing.domain.entity
  configuration:
    #mybatis开启驼峰自动转换
    map-underscore-to-camel-case: true
    #cache-enabled: false
    #local-cache-scope: statement

jasypt:
  encryptor:
    password: shanbing.top#shanbing.top@shanbing.top
#分页大小
pageSize: 20

#收件人
toMail: shan.bing@foxmail.com

QRCodeImgPath: qrcode

deploy:
  env: pro