server:
  port: 9110
spring:
  profiles:
    active: dev   #spring.profiles.active jar启动配置里更改环境
  application:
    name: comment-service


#mybatis相关配置
mybatis:
  mapperLocations: classpath:mapper/**/*.xml
  typeAliasesPackage: top.shanbing.domain.entity
  configuration:
    #mybatis开启驼峰自动转换
    map-underscore-to-camel-case: true
    #cache-enabled: false
    #local-cache-scope: statement

#分页大小
pageSize: 20
#限流大小
rateLimiter: 10

deploy:
  env: pro